# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1148_SipaJZBbbPxYk4gf-kBnXRAo3oMZ
"""

import SteveChessoardSmith.ChessBoard